### ISSUE TITLE
How to run sample? Manifest merger error?

### ISSUE THREAD

**Issue by ColtonIdle** [touchlab/compose-swift-bridge#1]
Trying to run the sample and getting an error regarding manifest merger. Can we get a snippet in the readme on how we run it?

**Comment by KevinSchildhorn** [comment]
Could you share the error here? Plus any additional context that might be relevant?

**Comment by DevSrSouza** [comment]
This is probably because the Sample Android module uses Google Maps and is missing the `MAPS_API_KEY` property at the `local.properties`.

Can you try to set a Google Maps key and see if works for you? https://developers.google.com/maps/documentation/android-sdk/get-api-key

**Comment by ColtonIdle** [comment]
Okay. I genereated a map key, but where am I supposed to put it? local.properties?

**Comment by ColtonIdle** [comment]
And where do I insert the maps key for ios?

**Comment by KevinSchildhorn** [comment]
For iOS you should not need an API key as it's using the Native MapKit

**Comment by KevinSchildhorn** [comment]
> This is probably because the Sample Android module uses Google Maps and is missing the `MAPS_API_KEY` property at the `local.properties`.

In the `local.properties`

**Comment by ColtonIdle** [comment]
Ah I didn't realize local.properties could insert things into the manifest. sorry, i thought you had to do manifest placeholders or something in build.gradle.
also. TIL that native mapkit doesnt require an api key!
