### ISSUE TITLE
ComposeNativeViewFactory has no corresponding expected declaration

### ISSUE THREAD

**Issue by rschattauer** [touchlab/compose-swift-bridge#3]
Repository to reproduce: https://github.com/rschattauer/compose_multiplatform/tree/swift-bridge

Hi!

First: Thank you for doing all this amazing KMP/CMP stuff!

Second:
I am trying to implement compose swift bridge as third solution (manual bridge for UIKit and SwiftUI are the others) into my mapbox playground repository. Following the tutorial https://touchlab.co/composeswiftbridge/tutorial but using 0.1.0 instead of 0.1.0-SNAPSHOT because I can't seem to find the snapshot and 0.1.0 has been released, I get up until step "2.2 Providing the Factory Interface that will come from iOS". https://touchlab.co/composeswiftbridge/tutorial#22-providing-the-factory-interface-that-will-come-from-ios

Once I call the gradle task `linkDebugFrameworkIosArm64` to run it fails with
`e: file:///Users/.../compose_multiplatform/shared/build/generated/ksp/iosArm64/iosArm64Main/kotlin/co/touchlab/compose/swift/bridge/ComposeSharedFactory.ios.kt:10:25 'actual interface ComposeSharedFactory : Any' has no corresponding expected declaration`
Also the created Map.ios.kt can't seem to find the import for `co.touchlab.compose.swift.bridge.LocalSharedFactory`.

What am I doing wrong?

Also I would like to have the generated file not being called `Map.ios.kt` as it may clash with an already existing `Map.ios.kt` that I created for other expect/actual fun/val. Maybe as suggestion to add another Suffix, like the factoryName, so it's MapShared.ios.kt (or MapNativeView.ios.kt by default)

**Comment by DevSrSouza** [comment]
I document a Gradle configuration with the wrong type, I will update our docs. You need to change the Task type to `org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask<*>` here https://github.com/rschattauer/compose_multiplatform/commit/0b8375b496141e7f053cc8c3d01b3e06ebf0fa6c#diff-120ae31c35b5a3341ab981cbe6469c705c985967aeb1abafc84823922f5292b2R50-R56

```kotlin
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask<*>>().configureEach {
    if (name != "kspCommonMainKotlinMetadata") {
        dependsOn("kspCommonMainKotlinMetadata")
    }
}
```

**Comment by rschattauer** [comment]
Thank you, that works now. But now I am stuck at 2.4 https://touchlab.co/composeswiftbridge/tutorial#24-implementing-the-factory-protocol because `SharedFactory` is not the type expected, but `ComposeSharedFactory` which hasn't 
```
func createSwiftBridgeMap(observable: shared.SwiftBridgeMapObservable) -> AnyView {
```
but
```
func createSwiftBridgeMap(contentPadding: any Foundation_layoutPaddingValues, polygons: [Polygon]) -> KotlinPair<UIViewController, any SwiftBridgeMapDelegate> {
```
but I would like the Observable to use as
```
struct BridgeSwiftUIMap: View {
    
    @ObservedObject var observable: SwiftBridgeMapObservable
    ...
```
Anything I am missing? Tutorial is also different here. Forced pushed the branch on my repository again, if you are so kind could you show me the right direction again?

**Comment by DevSrSouza** [comment]
This issue I think is related to this line here: https://github.com/rschattauer/compose_multiplatform/commit/eeaf41a652ad55625f64ac4a081345e09d660ae4#diff-4acb7d686f1fbf01d4f56e4acf3281da1f1a7748a9c3480824aac7da5243b078R7

That is caused by the used of the MainViewControllerKt instead of the SKIE Global Functions, this is documented at the end of the tutorial: https://touchlab.co/composeswiftbridge/tutorial#troubleshooting

**Comment by rschattauer** [comment]
Oh wow, I feel stupid for not seeing that. Thanks a lot.

Any chance to let us set values for UIKitInteropProperties? Otherwise I can't navigate around the map. Since Compose 1.7.0 this is required for maps. Same issue on your sample.
```
properties = UIKitInteropProperties(
    interactionMode = UIKitInteropInteractionMode.NonCooperative,
    ...
),
```

**Comment by DevSrSouza** [comment]
That can be done by using the custom interop composable function Annotation or KSP property: https://touchlab.co/composeswiftbridge#configuring-the-interoperability-function

**Comment by rschattauer** [comment]
Thanks. Achieved everything.
